"use client";
import { FormEvent, useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

export default function AdminPage() { const [email, setEmail] = useState(""); const [message, setMessage] = useState(""); const [loggedIn, setLoggedIn] = useState(false); const [profile, setProfile] = useState({ username: "", display_name: "", bio: "", category: "Lifestyle", avatar_url: "", status: "draft" });
  useEffect(() => { if (!supabase) return; supabase.auth.getSession().then(({ data }) => setLoggedIn(Boolean(data.session))); const { data: listener } = supabase.auth.onAuthStateChange((_event, session) => setLoggedIn(Boolean(session))); return () => listener.subscription.unsubscribe(); }, []);
  async function login(e: FormEvent) { e.preventDefault(); if (!supabase) return setMessage("Tambahkan NEXT_PUBLIC_SUPABASE_URL dan NEXT_PUBLIC_SUPABASE_ANON_KEY terlebih dahulu."); const { error } = await supabase.auth.signInWithOtp({ email }); setMessage(error?.message ?? "Magic link sudah dikirim ke email admin."); }
  async function save(e: FormEvent) { e.preventDefault(); if (!supabase) return; const { error } = await supabase.from("profiles").insert(profile); setMessage(error?.message ?? "Profile tersimpan sebagai draft."); }
  if (!loggedIn) return <main className="admin-wrap"><div className="brand"><span className="brand-mark">P</span> picnic club admin</div><div className="admin-card"><div className="eyebrow">Private workspace</div><h2>Welcome back.</h2><p className="hero-copy">Login admin menggunakan magic link Supabase.</p><form className="admin-form" onSubmit={login}><label>Email admin<input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="admin@picnicclub.id" /></label><button className="button-dark" type="submit">Send magic link</button></form>{message && <p className="error">{message}</p>}</div></main>;
  return <main className="admin-wrap"><div className="brand"><span className="brand-mark">P</span> picnic club admin</div><div className="admin-card"><div className="eyebrow">Profiles / new</div><h2>Create creator.</h2><form className="admin-form" onSubmit={save}><div className="admin-row"><label>Username<input required value={profile.username} onChange={(e) => setProfile({ ...profile, username: e.target.value.toLowerCase() })} placeholder="nama.creator" /></label><label>Display name<input required value={profile.display_name} onChange={(e) => setProfile({ ...profile, display_name: e.target.value })} /></label></div><label>Bio<textarea rows={3} value={profile.bio} onChange={(e) => setProfile({ ...profile, bio: e.target.value })} /></label><div className="admin-row"><label>Category<input value={profile.category} onChange={(e) => setProfile({ ...profile, category: e.target.value })} /></label><label>Avatar URL<input type="url" value={profile.avatar_url} onChange={(e) => setProfile({ ...profile, avatar_url: e.target.value })} placeholder="https://..." /></label></div><button className="button-dark" type="submit">Save draft</button></form>{message && <p>{message}</p>}</div></main>; }
