import Link from "next/link";
import { CreatorCard } from "./components/creator-card";
import { SiteNav } from "./components/site-nav";
import { getPublishedProfiles } from "@/lib/data";

export default async function Home() {
  const profiles = await getPublishedProfiles();
  const featured = profiles.filter((profile) => profile.is_featured).slice(0, 8);
  return <main className="site-shell"><SiteNav /><section className="hero"><div><div className="eyebrow">Creator commerce ecosystem / 001</div><h1>More than an agency<span style={{ color: "var(--orange)" }}>.</span></h1><p className="hero-copy">Rumah bagi para creator dan affiliator terbaik Indonesia. Grow your influence, income, and network together.</p><div className="hero-actions"><Link className="button-lime" href="https://forms.gle/yEmDWsFd1q5DHjjP8">Join as creator ↗</Link><Link className="button-outline" href="https://wa.me/62895364547187">Collaborate with us</Link></div></div><div className="orbit"><img className="avatar" src={featured[0]?.avatar_url ?? "https://i.pravatar.cc/160?img=12"} alt="" /><img className="avatar" src={featured[1]?.avatar_url ?? "https://i.pravatar.cc/160?img=11"} alt="" /><img className="avatar" src={featured[2]?.avatar_url ?? "https://i.pravatar.cc/160?img=13"} alt="" /><img className="avatar" src={featured[3]?.avatar_url ?? "https://i.pravatar.cc/160?img=14"} alt="" /><div className="orbit-center">2000+<br />creators</div></div></section><div className="band"><span>●</span> Build together / learn together / win together <span>●</span> Indonesia&apos;s largest affiliate community <span>●</span></div><section className="section"><div className="section-head"><div><div className="eyebrow">The people / 002</div><h2>Meet the<br />community.</h2></div><p className="section-note">Real people, real recommendations. Explore the creators building the next wave of commerce in Indonesia.</p></div><div className="creator-grid">{featured.slice(0, 4).map((profile) => <CreatorCard key={profile.id} profile={profile} />)}</div><div style={{ marginTop: 28 }}><Link className="button-dark" href="/members">Explore all creators ↗</Link></div></section><section id="about" className="section" style={{ background: "var(--lime)", maxWidth: "none", paddingLeft: "max(28px, calc((100% - 1184px) / 2))", paddingRight: "max(28px, calc((100% - 1184px) / 2))" }}><div className="eyebrow">Why Picnic Club / 003</div><h2>We make creator<br />growth feel less lonely.</h2><p className="hero-copy" style={{ color: "var(--ink)", marginTop: 26 }}>Dari training, mentoring, networking, sampai peluang kolaborasi dengan brand. Picnic Club hadir untuk membantu creator tumbuh dengan support yang nyata.</p></section><footer className="footer"><div className="footer-inner"><div><div className="brand"><span className="brand-mark" style={{ background: "var(--lime)", color: "var(--ink)" }}>P</span> picnic club</div><p>Indonesia&apos;s home for creators, affiliators, and brands that want to grow together.</p></div><Link className="button-lime" href="https://wa.me/62895364547187">Start a conversation ↗</Link></div><div className="footer-bottom">© 2026 Picnic Club · Privacy · Terms</div></footer></main>;
}
