"use client";

import { FormEvent, useEffect, useState } from "react";
import { CmsSection } from "../cms-section";
import { Brand } from "@/lib/brand-data";
import { supabase } from "@/lib/supabase";

const emptyBrand = { name: "", logo_url: "", website_url: "", sort_order: 0, is_active: true };

export default function BrandsCmsPage() {
  const [brands, setBrands] = useState<Brand[]>([]);
  const [form, setForm] = useState(emptyBrand);
  const [logoFile, setLogoFile] = useState<File | null>(null);
  const [editing, setEditing] = useState<string | null>(null);
  const [message, setMessage] = useState("");
  useEffect(() => { if (!supabase) return; supabase.from("brands").select("*").order("sort_order").then(({ data, error }) => { if (error) setMessage(error.message); setBrands((data as Brand[]) ?? []); }); }, []);
  async function saveBrand(event: FormEvent) { event.preventDefault(); if (!supabase) return; if (!form.name || (!form.logo_url && !logoFile)) return setMessage("Tambahkan logo melalui upload atau URL."); let logoUrl = form.logo_url; if (logoFile) { if (!logoFile.type.startsWith("image/")) return setMessage("Logo harus berupa file gambar."); if (logoFile.size > 5 * 1024 * 1024) return setMessage("Ukuran logo maksimal 5 MB."); const path = `brand-${crypto.randomUUID()}-${logoFile.name.replace(/[^a-zA-Z0-9._-]/g, "-")}`; const { error: uploadError } = await supabase.storage.from("Avatar").upload(path, logoFile, { contentType: logoFile.type, upsert: false }); if (uploadError) return setMessage(uploadError.message); logoUrl = supabase.storage.from("Avatar").getPublicUrl(path).data.publicUrl; } const result = editing ? await supabase.from("brands").update({ ...form, logo_url: logoUrl }).eq("id", editing) : await supabase.from("brands").insert({ ...form, logo_url: logoUrl }); if (result.error) return setMessage(result.error.message); setMessage(editing ? "Brand updated." : "Brand added."); setForm(emptyBrand); setLogoFile(null); setEditing(null); const { data } = await supabase.from("brands").select("*").order("sort_order"); setBrands((data as Brand[]) ?? []); }
  async function removeBrand(id: string) { if (!supabase) return; const { error } = await supabase.from("brands").delete().eq("id", id); if (error) return setMessage(error.message); setBrands(brands.filter((brand) => brand.id !== id)); setMessage("Brand removed."); }
  return <CmsSection eyebrow="Brands / 005" title={<>Build brand<br />trust.</>} description="Kelola logo dan partner yang tampil di brand marquee homepage."><section className="admin-card"><div className="eyebrow">Brand partners</div><h2>{editing ? "Edit brand." : "Add a brand."}</h2><form className="admin-form" onSubmit={saveBrand}><div className="admin-row"><label>Brand name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Upload logo<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={(event) => setLogoFile(event.target.files?.[0] ?? null)} /><small style={{ color: "var(--muted)" }}>PNG, JPG, WebP, atau SVG. Maks. 5 MB.</small></label></div><div className="admin-row"><label>Logo URL (optional)<input type="url" value={form.logo_url} onChange={(event) => setForm({ ...form, logo_url: event.target.value })} placeholder="Gunakan URL jika tidak upload file" /></label><label>Website URL<input type="url" value={form.website_url} onChange={(event) => setForm({ ...form, website_url: event.target.value })} placeholder="Optional" /></label></div><label>Display order<input type="number" value={form.sort_order} onChange={(event) => setForm({ ...form, sort_order: Number(event.target.value) })} /></label><label className="checkbox-label"><input type="checkbox" checked={form.is_active} onChange={(event) => setForm({ ...form, is_active: event.target.checked })} /> Show in homepage marquee</label><div className="form-actions"><button className="button-dark" type="submit">{editing ? "Update brand" : "Add brand"}</button>{editing && <button className="button-outline" type="button" onClick={() => { setEditing(null); setForm(emptyBrand); setLogoFile(null); }}>Cancel</button>}</div></form></section><section className="admin-card"><div className="cms-table">{brands.map((brand) => <div className="brand-admin-row" key={brand.id}><img src={brand.logo_url} alt={brand.name} /><div><strong>{brand.name}</strong><small>{brand.is_active ? "Visible on homepage" : "Hidden"} · order {brand.sort_order}</small></div><button className="button-outline" type="button" onClick={() => { setEditing(brand.id); setForm({ name: brand.name, logo_url: brand.logo_url, website_url: brand.website_url, sort_order: brand.sort_order, is_active: brand.is_active }); setLogoFile(null); }}>Edit</button><button className="button-outline" type="button" onClick={() => removeBrand(brand.id)}>Remove</button></div>)}</div>{message && <p className="cms-message">{message}</p>}</section></CmsSection>;
}
